### ISSUE TITLE
Migration plan for font size (fs) utility classes

### ISSUE THREAD

**Issue by jabbett** [coggen/kezuri#16]
Craft provides a set of font-size utility classes, which are overridden in Sharpen Web Components:

```
.fs-1 {
  font-family: $font-titleBold;
  font-size: 36px;
}

.fs-2 {
  font-family: $font-titleBold;
  font-size: 30px;
}

.fs-3 {
  font-family: $font-titleBold;
  font-size: 26px;
}

.fs-4 {
  font-family: $font-titleBold;
  font-size: 18px;
}

.fs-5 {
  font-family: $font-regular;
  font-size: 20px;
}

.fs-6,
.fs-7 {
  font-family: $font-regular;
  font-size: 18px;
}
```

**Comment by jabbett** [comment]
Note in the above that a font-weight customization is being done alongside the font sizes. Kezuri takes a different approach to this, so there are some options for exactly how we migrate.

## Font size

Kezuri defines a set of font size tokens...

```
  --font-size-xs:    0.875rem;  // 14px
  --font-size-sm:    1rem;      // 16px
  --font-size-md:    1.125rem;  // 18px
  --font-size-lg:    1.25rem;   // 20px
  --font-size-xl:    1.375rem;  // 22px
  --font-size-2xl:   1.625rem;  // 26px
  --font-size-3xl:   2.125rem;  // 34px
  --font-size-4xl:   2.75rem;   // 44px
  --font-size-5xl:   4rem;      // 64px
```

...and provides utility classes for font size:

```css
.sharpen-text-xs  { font-size: var(--font-size-xs); }
.sharpen-text-sm  { font-size: var(--font-size-sm); }
.sharpen-text-md  { font-size: var(--font-size-md); }
.sharpen-text-lg  { font-size: var(--font-size-lg); }
.sharpen-text-xl  { font-size: var(--font-size-xl); }
.sharpen-text-2xl { font-size: var(--font-size-2xl); }
.sharpen-text-3xl { font-size: var(--font-size-3xl); }
.sharpen-text-4xl { font-size: var(--font-size-4xl); }
.sharpen-text-5xl { font-size: var(--font-size-5xl); }
```

The closest mapping would be:

| Craft | Kezuri |
| --- | --- |
| `fs-1` | `sharpen-text-4xl` |
| `fs-2` | `sharpen-text-3xl` |
| `fs-3` | `sharpen-text-2xl` |
| `fs-4` | `sharpen-text-xl` |
| `fs-5` | `sharpen-text-lg` |
| `fs-6`, `fs-7` | `sharpen-text-md` |

## Font weight

Kezuri's approach to font weight is to reserve the semibold weight for headings, or to use the `strong` tag for inline bolding.

Kezuri provides a set of heading classes that handle both font weight and size, in both serif and sans-serif:

```css
.sharpen-heading-md, .sharpen-heading-md-sans { font-size: var(--font-size-md); }
.sharpen-heading-lg, .sharpen-heading-lg-sans { font-size: var(--font-size-lg); }
.sharpen-heading-xl, .sharpen-heading-xl-sans { font-size: var(--font-size-xl); }
.sharpen-heading-2xl, .sharpen-heading-2xl-sans { font-size: var(--font-size-2xl); }
.sharpen-heading-3xl, .sharpen-heading-3xl-sans { font-size: var(--font-size-3xl); }
.sharpen-heading-4xl, .sharpen-heading-4xl-sans { font-size: var(--font-size-4xl); }
.sharpen-heading-5xl, .sharpen-heading-5xl-sans { font-size: var(--font-size-5xl); }
```

In case where you would apply both a larger font size and a bolder font weight, you'd probably migrate to a heading class, e.g.

```
<div class="fs-7 text-gray-600 fw-bold mt-1">
  <%= record.subject.decorate.display_age_or_grade %>
</div>
```

becomes

```
<div class="sharpen-heading-md sharpen-text--muted sharpen-mt-1">
  <%= record.subject.decorate.display_age_or_grade %>
</div>
```

* `fs-7` and `fw-bold` roll up into `sharpen-heading-md`
* `text-gray-600` is replaced with `sharpen-text--muted` (applying color `var(--color-gray-1)`)
* `mt-1` becomes `sharpen-mt-1`
